using static System.Math;
using static System.Console;
using static gi_rot;
using static matrix;
using static vector;

public class main{
	static int Main() {
	matrix A= new matrix(3,3); //matrix taken from wiki 
	A[0,0]=6; A[0,1]=5; A[0,2]=0;
	A[1,0]=5; A[1,1]=1; A[1,2]=4;	
	A[2,0]=0; A[2,1]=4; A[2,2]=3;

	gi_rot a=new gi_rot(A);
	matrix a1=a.A;
	
	WriteLine("Matrix generated by function:");
		for(int n=0; n<A.size1;n++){
			for(int n1=0;n1<A.size2;n1++){
			Write($"{a1[n,n1]}	");
			}//end for
		Write("\n");
		}//end for
	
	vector b= new vector(A.size1);
	b[0]=1; b[1]=3; b[2]=-1;
	
	vector x =a.solve(b);
	vector ax= A*x;
	WriteLine($"Test Ax=b:");
	for(int n1=0; n1<b.size;n1++){
		WriteLine($"Ax=	{ax[n1]},	b=	{b[n1]}");
		}
	



	return 0;}//end main}
}//end class main
